package org.vaadin.addon.formbinder.test;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.Slider;
import com.vaadin.ui.TextField;

/**
 * This is a view class to demonstrate pre created fields pattern and the
 * PreCreatedFieldsHelper. Pay attention to how fields have been named. This
 * example class is built with Vaadin VisualEditor, but could just as well be
 * manually custom tailored as long as fields are properly named.
 */
public class MyExamplePojoView extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private PopupDateField birthDateField;
	@AutoGenerated
	private TextField lastNameField;
	@AutoGenerated
	private TextField firstNameField;
	@AutoGenerated
	private Slider weightField;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public MyExamplePojoView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// No custom code required as this is used just as a view
		
		weightField.setMin(0);
		weightField.setMax(150);
		
		// for testing
		firstNameField.setDebugId(getClass().getSimpleName() + ".firstname");

	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100px");
		
		// weightField
		weightField = new Slider();
		weightField.setCaption("Weight (kg)");
		weightField.setImmediate(false);
		weightField.setWidth("480px");
		weightField.setHeight("6px");
		mainLayout.addComponent(weightField, "top:68.0px;left:20.0px;");
		
		// firstNameField
		firstNameField = new TextField();
		firstNameField.setCaption("First name");
		firstNameField.setImmediate(false);
		firstNameField.setWidth("80px");
		firstNameField.setHeight("-1px");
		firstNameField.setSecret(false);
		mainLayout.addComponent(firstNameField, "top:20.0px;left:20.0px;");
		
		// lastNameField
		lastNameField = new TextField();
		lastNameField.setCaption("Last name");
		lastNameField.setImmediate(false);
		lastNameField.setWidth("197px");
		lastNameField.setHeight("-1px");
		lastNameField.setSecret(false);
		mainLayout.addComponent(lastNameField, "top:20.0px;left:120.0px;");
		
		// birthDateField
		birthDateField = new PopupDateField();
		birthDateField.setCaption("Birth date");
		birthDateField.setImmediate(false);
		birthDateField.setWidth("-1px");
		birthDateField.setHeight("-1px");
		birthDateField.setInvalidAllowed(false);
		mainLayout.addComponent(birthDateField, "top:20.0px;left:337.0px;");
		
		return mainLayout;
	}

}
