package org.vaadin.addon.formbinder.test;

import org.vaadin.addon.formbinder.FormFieldMatch;
import org.vaadin.addon.formbinder.FormView;
import org.vaadin.addon.formbinder.PropertyId;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.Slider;
import com.vaadin.ui.TextField;

/**
 * This is a view class to demonstrate pre created fields pattern and the
 * PreCreatedFieldsHelper. When this view is used, views are mapped with
 * annotations. This example class is built with Vaadin VisualEditor, but could
 * just as well be manually custom tailored. Only annotations are added afterwards.
 */
@FormView(matchFieldsBy = FormFieldMatch.ANNOTATION)
public class MyExamplePojoViewWithCustomNames extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	@PropertyId("birthDate")
	private PopupDateField birthDateFieldWithOutNamingConvention;
	@AutoGenerated
	@PropertyId("lastName")
	private TextField lastNameFieldWithOddJavaName;
	@AutoGenerated
	@PropertyId("firstName")
	private TextField firstNameFieldWithOddJavaName;
	@AutoGenerated
	@PropertyId("weight")
	private Slider weightFieldWithOddJavaName;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public MyExamplePojoViewWithCustomNames() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// No custom code required as this is used just as a view

		weightFieldWithOddJavaName.setMin(0);
		weightFieldWithOddJavaName.setMax(150);
		
		// for testing
		firstNameFieldWithOddJavaName.setDebugId(getClass().getSimpleName() + ".firstname");
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100px");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100px");

		// weightField
		weightFieldWithOddJavaName = new Slider();
		weightFieldWithOddJavaName.setCaption("Weight (kg)");
		weightFieldWithOddJavaName.setImmediate(false);
		weightFieldWithOddJavaName.setWidth("480px");
		weightFieldWithOddJavaName.setHeight("6px");
		mainLayout.addComponent(weightFieldWithOddJavaName, "top:68.0px;left:20.0px;");

		// firstNameField
		firstNameFieldWithOddJavaName = new TextField();
		firstNameFieldWithOddJavaName.setCaption("First name");
		firstNameFieldWithOddJavaName.setImmediate(false);
		firstNameFieldWithOddJavaName.setWidth("80px");
		firstNameFieldWithOddJavaName.setHeight("-1px");
		firstNameFieldWithOddJavaName.setSecret(false);
		mainLayout.addComponent(firstNameFieldWithOddJavaName, "top:20.0px;left:20.0px;");

		// lastNameField
		lastNameFieldWithOddJavaName = new TextField();
		lastNameFieldWithOddJavaName.setCaption("Last name");
		lastNameFieldWithOddJavaName.setImmediate(false);
		lastNameFieldWithOddJavaName.setWidth("197px");
		lastNameFieldWithOddJavaName.setHeight("-1px");
		lastNameFieldWithOddJavaName.setSecret(false);
		mainLayout.addComponent(lastNameFieldWithOddJavaName, "top:20.0px;left:120.0px;");

		// birthDateField
		birthDateFieldWithOutNamingConvention = new PopupDateField();
		birthDateFieldWithOutNamingConvention.setCaption("Birth date");
		birthDateFieldWithOutNamingConvention.setImmediate(false);
		birthDateFieldWithOutNamingConvention.setWidth("-1px");
		birthDateFieldWithOutNamingConvention.setHeight("-1px");
		birthDateFieldWithOutNamingConvention.setInvalidAllowed(false);
		mainLayout.addComponent(birthDateFieldWithOutNamingConvention, "top:20.0px;left:337.0px;");

		return mainLayout;
	}

}
